apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accountms
    version: v1
  name: accountms
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  replicas: 1
  selector:
    matchLabels:
      app: accountms
      version: v1
  template:
    metadata:
      labels:
        app: accountms
        version: v1
    spec:
      containers:
      - image: gcr.io/sinuous-photon-284101/accountmsv101:6
        imagePullPolicy: Always
        name: accountms
        ports:
        - name: httpport
          containerPort: 8080
          hostPort: 8080