apiVersion: v1
kind: Service
metadata:
  labels:
    app: accountms
    version: v1
  name: accountms
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: accountms
    version: v1
  type: NodePort