apiVersion: v1
kind: Service
metadata:
  labels:
    app: shoppingwebms
    version: v1
  name: shoppingwebms
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: shoppingwebms
    version: v1
  type: NodePort