apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shoppingwebms
    version: v1
  name: shoppingwebms
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  replicas: 1
  selector:
    matchLabels:
      app: shoppingwebms
      version: v1
  template:
    metadata:
      labels:
        app: shoppingwebms
        version: v1
    spec:
      containers:
      - image: gcr.io/sinuous-photon-284101/shoppingwebmsv101:7
        imagePullPolicy: Always
        name: shoppingwebms
        ports:
        - name: httpport
          containerPort: 9090
          hostPort: 9090